# search terms for deals

searchTerms = [
	'Super Smash Bros', 
	'Switch', 
	'Addicted to Audio',
	'AddictedtoAudio.com',
	'PC', 
	'Viewsonic', 
	'Red wing', 
	'RM Williams', 
	'Tech Fast',
	'Google nest',
	'logitech',
	'Nintendo',
	'Samsung',
	'vornado',
	'Sony zx500',
	'Sony zx300',
	'Sony IER-M9',
	'Campfire audio',
	'hikari',
	'dainichi',
	'Viewsonic',
	'Ubiquiti',
	'Uniqlo',
]